name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      # Yeh line saare packages layegi, bina kisi faltu error/script ke
      - name: Install dependencies
        run: cd yaad-se-dawai && yarn install --ignore-scripts
          
      - name: Install EAS CLI
        run: npm install -g eas-cli
        
      - name: Build APK
        run: cd yaad-se-dawai && eas build --platform android --profile preview --non-interactive --no-wait
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
